### ISSUE TITLE
how can I get the link fields on backend? 

### ISSUE THREAD

**Issue by mypetertw** [editor-js/link#12]
when I post link with endpoint, how can I get the link fields on backend? (PHP) 
i means "methods"

**Comment by prashant1k99** [comment]
I found that the request is made like this:
`https://localhost:8080/endpoint?url=<encoded-url>`

so it is a query parameter:
In express:
```js
app.get('/endpoint', (req, res) => {
  const urlToFetch = req.query.url;
  //Do your logic and send data
})
```

**Comment by arhziz** [comment]
hello, please i'm having trouble the "<encoded-url>" data

**Comment by neSpecc** [comment]
If the question is still relevant, open the new issue.
