### ISSUE TITLE
[Bug] Couldn't parse response due to external API changes

### ISSUE THREAD

**Issue by m-alzam** [editor-js/link#25]
Hi,

The [`@codexteam/ajax`](https://github.com/codex-team/ajax) library have changed the way data is returned in `ajax.get()` method. This is breaking the main functionality of the link pluging. [This commit](https://github.com/codex-team/ajax/commit/83d3339833860da582562f1268658c72a6106938) made the change.

Here is the code:
https://github.com/editor-js/link/blob/f076c97dcb8824d3d40e064f1a63d91dd70e94ea/src/index.js#L363-L386

Best.

**Comment by KonstantinKudelko** [comment]
@m-alzam faced with same issue there:
![image](https://user-images.githubusercontent.com/16194085/83981505-1fc45280-a927-11ea-987e-d470dd69eb6e.png)

**Comment by wutsi** [comment]
any update on this?
This component is broken on our site in production
Thanks
